# Generated by Django 4.2.15 on 2024-08-30 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_rename__file_tickettemplate_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickettemplate",
            old_name="file",
            new_name="_file",
        ),
    ]
