repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [--check]
-   repo: local
    hooks:
    - id: tests
      name: run tests
      entry: poetry run test
      language: system
      stages: [commit]
-   repo: local
    hooks:
    - id: lint
      name: run lint
      entry: poetry run lint
      language: system
      stages: [commit]