# Generated by Django 3.2.7 on 2021-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplatformchoice',
            name='auth_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
