# Generated by Django 3.2.8 on 2021-10-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_id_event_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="key",
            new_name="ID",
        ),
    ]
