# Generated by Django 3.2.8 on 2021-10-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_key_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ID',
            new_name='id',
        ),
    ]
