# Generated by Django 3.2.8 on 2021-10-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20211028_1819"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtemplate",
            name="event",
        ),
    ]
