# Generated by Django 3.2.8 on 2021-10-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_eventtemplate_event'),
        ('tickets', '0002_auto_20211029_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTemplate',
        ),
    ]
