# Generated by Django 3.2.7 on 2021-10-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='url',
            field=models.URLField(default='', max_length=1024),
        ),
    ]
