# Generated by Django 3.2.8 on 2021-10-27 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="id",
            new_name="key",
        ),
    ]
