# Generated by Django 3.2.8 on 2021-10-28 18:19

import django.core.validators
from django.db import migrations, models

import applications.core.services


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_auto_20211027_2059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=applications.core.services.EventFileNameGeneratorService.generate,
            ),
        ),
        migrations.AlterField(
            model_name="eventtemplate",
            name="template",
            field=models.FileField(
                upload_to="media/tickets/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.DeleteModel(
            name="EventTicket",
        ),
    ]
