# Generated by Django 3.2.8 on 2021-10-29 12:51

from django.db import migrations, models

import applications.core.services


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_delete_eventtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=applications.core.services.EventFileNameGeneratorService.generate,
            ),
        ),
    ]
