# Generated by Django 4.2.15 on 2024-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_followedhashtag_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("1", "Music Festival"),
                    ("2", "Art Exhibition"),
                    ("3", "Concert"),
                    ("4", "Theatre performance"),
                    ("5", "Movie Festival"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
