# Generated by Django 3.2.8 on 2021-10-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_auto_20211029_0930"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickettemplate",
            old_name="template",
            new_name="_file",
        ),
    ]
